version: '3.8'

services:
  # Основное приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./visitors.db:/app/visitors.db:rw
      - ./backups:/app/backups:rw
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - tornado-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Административное приложение
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    ports:
      - "5000:5000"
    volumes:
      - ./visitors.db:/app/visitors.db:rw
      - ./backups:/app/backups:rw
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - tornado-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tornado-network:
    driver: bridge

volumes:
  db-data:


